#!/bin/bash
set -e

INCORRECT_EMAIL=${1:? missing incorrect email}
CORRECT_EMAIL=${2:? missing correct email}
CORRECT_NAME=${3:? missing correct name}

echo INCORRECT_EMAIL $INCORRECT_EMAIL
echo CORRECT_EMAIL $CORRECT_EMAIL
echo CORRECT_NAME $CORRECT_NAME

git filter-branch --env-filter 'if [ "$GIT_AUTHOR_EMAIL" = "$INCORRECT_EMAIL" ]; then
     GIT_AUTHOR_EMAIL="$CORRECT_EMAIL";
     GIT_AUTHOR_NAME="$CORRECT_NAME";
     GIT_COMMITTER_EMAIL=$GIT_AUTHOR_EMAIL;
     GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME"; fi' -- --all
