#!/usr/bin/env bash
# set -e
# set -o pipefail

goclean() {
 local pkg=$1; shift || return 1
 local ost
 local cnt
 local scr
 
 echo $pkg
 # Clean removes object files from package source directories (ignore error)
 go clean -i $pkg # &>/dev/null
 echo clean

 # Set local variables
#  [[ "$(uname -m)" == "x86_64" ]] \
#  && ost="$(uname)";ost="${ost,,}_amd64" \
 cnt="${pkg//[^\/]}"

#  echo ost: $ost
 echo cnt: $cnt

 # Delete the source directory and compiled package directory(ies)
 if (("${#cnt}" == "2")); then
  rm -rf "${GOPATH%%:*}/src/${pkg%/*}"
  # rm -rf "${GOPATH%%:*}/pkg/${ost}/${pkg%/*}"
  rm -rf "${GOPATH%%:*}/pkg/${pkg%/*}"
 elif (("${#cnt}" > "2")); then
  rm -rf "${GOPATH%%:*}/src/${pkg%/*/*}"
  # rm -rf "${GOPATH%%:*}/pkg/${ost}/${pkg%/*/*}"
  rm -rf "${GOPATH%%:*}/pkg/${pkg%/*/*}"
 fi

 # Reload the current shell
 source ~/.zshrc
}

(return 0 2>/dev/null) && return

goclean $@
