#!/bin/sh
set -e
npm install -g karma-mocha-reporter karma-chai karma-expect karma-coverage karma-html2js-preprocessor karma-fixture karma-phantomjs-launcher karma-browserify karma-mocha karma-chrome-launcher karma-coffee-preprocessor
