#!/bin/sh
set -e

kubectl="$HOME/code/github/ua/team-kube/kubectl.sh"

cmd="$kubectl exec  -t $($kubectl get pods | grep $1 | grep Running | awk 'NR==1{print $1}') bash"
if [ "$2" = "echo" ]; then
  echo "$cmd"
  exit 0
fi


$cmd
