#!/bin/bash
NEXT_VERSION=$(npm version `npm version "$@" --no-git-tag-version --ignore-scripts | sed 's/\..\d*$//g'` --no-git-tag-version)
git commit -am "version bump $NEXT_VERSION unstable without tag"
